-- 实验二

--（1）单表查询（实现投影操作）
SELECT S_NAME, S_ADDRESS, S_PHONE
FROM SUPPLIER;

--（2）单表单条件查询（实现选择操作）
SELECT P_PARTKEY, P_NAME, P_RETAILPRICE
FROM PART
WHERE P_RETAILPRICE <= 500;

--（3）单表多条件查询
SELECT O_ORDERKEY, O_CUSTKEY, O_ORDERDATE, O_TOTALPRICE
FROM ORDERS
WHERE O_ORDERDATE >= DATEADD(WEEK, -1, GETDATE()) AND O_TOTALPRICE > 1000;

--（4）两表连接查询（实现笛卡尔积操作）
SELECT S.S_NAME, S.S_ADDRESS, S.S_PHONE, N.N_NAME
FROM SUPPLIER S, NATION N;

--（5）两表连接查询（实现普通连接操作，任意两个列做大于、小于等连接操作）
SELECT P.P_PARTKEY, P.P_NAME, PS.PS_SUPPLYCOST
FROM PART P
JOIN PARTSUPP PS ON P.P_PARTKEY = PS.PS_PARTKEY
WHERE PS.PS_SUPPLYCOST > P.P_RETAILPRICE;

--（6）两表连接查询（实现等值连接操作）
SELECT S.S_NAME, S.S_ADDRESS, S.S_PHONE, N.N_NAME
FROM SUPPLIER S
JOIN NATION N ON S.S_NATIONKEY = N.N_NATIONKEY;

--（7）两表连接查询（实现自然连接操作）
SELECT P.P_PARTKEY, P.P_NAME, PS.PS_SUPPLYCOST
FROM PART P
JOIN PARTSUPP PS ON P.P_PARTKEY = PS.PS_PARTKEY
WHERE PS.PS_SUPPLYCOST > P.P_RETAILPRICE;

--（8）单表自身连接查询
SELECT S2.S_SUPPKEY, S2.S_NAME, S2.S_ADDRESS
FROM SUPPLIER S1
JOIN SUPPLIER S2 ON S1.S_NATIONKEY = S2.S_NATIONKEY
WHERE S1.S_NAME = '海大';

--（9）三表连接查询
SELECT O.O_ORDERKEY, O.O_TOTALPRICE, LI.L_PARTKEY, LI.L_QUANTITY, LI.L_EXTENDEDPRICE
FROM ORDERS O
JOIN LINEITEM LI ON O.O_ORDERKEY = LI.L_ORDERKEY
JOIN CUSTOMER C ON O.O_CUSTKEY = C.C_CUSTKEY
WHERE C.C_NAME = '苏举库';

--（10）四表连接查询
SELECT O.O_ORDERKEY, O.O_TOTALPRICE, LI.L_PARTKEY, PS.PS_SUPPLYCOST, LI.L_QUANTITY, LI.L_EXTENDEDPRICE
FROM ORDERS O
JOIN LINEITEM LI ON O.O_ORDERKEY = LI.L_ORDERKEY
JOIN PARTSUPP PS ON LI.L_PARTKEY = PS.PS_PARTKEY AND LI.L_SUPPKEY = PS.PS_SUPPKEY
JOIN CUSTOMER C ON O.O_CUSTKEY = C.C_CUSTKEY
WHERE C.C_NAME = '苏举库';

--（11）五表连接查询
SELECT O.O_ORDERKEY, O.O_TOTALPRICE, LI.L_PARTKEY, P.P_NAME, LI.L_QUANTITY, LI.L_EXTENDEDPRICE
FROM ORDERS O
JOIN LINEITEM LI ON O.O_ORDERKEY = LI.L_ORDERKEY
JOIN PART P ON LI.L_PARTKEY = P.P_PARTKEY
JOIN CUSTOMER C ON O.O_CUSTKEY = C.C_CUSTKEY
WHERE C.C_NAME = '苏举库';

--（12）六表连接查询
SELECT O.O_ORDERKEY, O.O_TOTALPRICE, LI.L_PARTKEY, S.S_NAME, P.P_NAME, LI.L_QUANTITY, LI.L_EXTENDEDPRICE
FROM ORDERS O
JOIN LINEITEM LI ON O.O_ORDERKEY = LI.L_ORDERKEY
JOIN PARTSUPP PS ON LI.L_PARTKEY = PS.PS_PARTKEY AND LI.L_SUPPKEY = PS.PS_SUPPKEY
JOIN SUPPLIER S ON PS.PS_SUPPKEY = S.S_SUPPKEY
JOIN PART P ON LI.L_PARTKEY = P.P_PARTKEY
JOIN CUSTOMER C ON O.O_CUSTKEY = C.C_CUSTKEY
WHERE C.C_NAME = '苏举库';

--（13）七表连接查询
SELECT O.O_ORDERKEY, O.O_TOTALPRICE, LI.L_PARTKEY, S.S_NAME, P.P_NAME, LI.L_QUANTITY, LI.L_EXTENDEDPRICE
FROM ORDERS O
JOIN LINEITEM LI ON O.O_ORDERKEY = LI.L_ORDERKEY
JOIN PARTSUPP PS ON LI.L_PARTKEY = PS.PS_PARTKEY AND LI.L_SUPPKEY = PS.PS_SUPPKEY
JOIN SUPPLIER S ON PS.PS_SUPPKEY = S.S_SUPPKEY
JOIN PART P ON LI.L_PARTKEY = P.P_PARTKEY
JOIN CUSTOMER C ON O.O_CUSTKEY = C.C_CUSTKEY
JOIN NATION N ON C.C_NATIONKEY = N.N_NATIONKEY
WHERE N.N_NAME = '中国';

--（14）八表连接查询
SELECT O.O_ORDERKEY, O.O_TOTALPRICE, LI.L_PARTKEY, S.S_NAME, P.P_NAME, LI.L_QUANTITY, LI.L_EXTENDEDPRICE
FROM ORDERS O
JOIN LINEITEM LI ON O.O_ORDERKEY = LI.L_ORDERKEY
JOIN PARTSUPP PS ON LI.L_PARTKEY = PS.PS_PARTKEY AND LI.L_SUPPKEY = PS.PS_SUPPKEY
JOIN SUPPLIER S ON PS.PS_SUPPKEY = S.S_SUPPKEY
JOIN PART P ON LI.L_PARTKEY = P.P_PARTKEY
JOIN CUSTOMER C ON O.O_CUSTKEY = C.C_CUSTKEY
JOIN NATION N ON C.C_NATIONKEY = N.N_NATIONKEY
JOIN REGION R ON N.N_REGIONKEY = R.R_REGIONKEY
WHERE R.R_NAME = '亚洲';
