-- 实验三

--（1）不带分组过滤条件的分组统计查询。
SELECT O_CUSTKEY, SUM(O_TOTALPRICE) AS TOTAL_ORDER_AMOUNT
FROM ORDERS
GROUP BY O_CUSTKEY;

--（2）带分组过滤条件的分组统计查询。
SELECT O_CUSTKEY, C_NAME, AVG(O_TOTALPRICE) AS AVG_ORDER_AMOUNT
FROM ORDERS
JOIN CUSTOMER ON ORDERS.O_CUSTKEY = CUSTOMER.C_CUSTKEY
GROUP BY O_CUSTKEY, C_NAME
HAVING AVG(O_TOTALPRICE) > 1000;

--（3）IN嵌套查询。
SELECT DISTINCT C_CUSTKEY, C_NAME
FROM CUSTOMER
WHERE C_CUSTKEY IN (
    SELECT O_CUSTKEY
    FROM ORDERS
    WHERE O_ORDERKEY IN (
        SELECT L_ORDERKEY
        FROM LINEITEM
        WHERE L_PARTKEY IN (
            SELECT P_PARTKEY
            FROM PART
            WHERE P_MFGR = '海大'
            AND P_NAME = '船舶模拟驾驶舱'
        )
    )
);

--（4）单层EXISTS嵌套查询。
SELECT C_CUSTKEY, C_NAME
FROM CUSTOMER C
WHERE NOT EXISTS (
    SELECT 1
    FROM ORDERS O
    JOIN LINEITEM LI ON O.O_ORDERKEY = LI.L_ORDERKEY
    JOIN PART P ON LI.L_PARTKEY = P.P_PARTKEY
    WHERE O.O_CUSTKEY = C.C_CUSTKEY
    AND P.P_MFGR = '海大'
    AND P.P_NAME = '船舶模拟驾驶舱'
);

--（5）双层EXISTS嵌套查询。
SELECT DISTINCT C_NAME
FROM CUSTOMER C1
WHERE NOT EXISTS (
    SELECT P_PARTKEY
    FROM PART P
    WHERE NOT EXISTS (
        SELECT 1
        FROM ORDERS O
        JOIN LINEITEM LI ON O.O_ORDERKEY = LI.L_ORDERKEY
        WHERE O.O_CUSTKEY = C1.C_CUSTKEY
        AND LI.L_PARTKEY = P.P_PARTKEY
    )
    AND P.P_PARTKEY IN (
        SELECT LI.L_PARTKEY
        FROM ORDERS O
        JOIN LINEITEM LI ON O.O_ORDERKEY = LI.L_ORDERKEY
        JOIN CUSTOMER C2 ON O.O_CUSTKEY = C2.C_CUSTKEY
        WHERE C2.C_NAME = '李四'
    )
);

--（6）集合查询(交、并、差各设计一个)。
--交集
SELECT P.P_PARTKEY, P.P_NAME
FROM PART P
JOIN LINEITEM LI ON P.P_PARTKEY = LI.L_PARTKEY
JOIN ORDERS O ON LI.L_ORDERKEY = O.O_ORDERKEY
JOIN CUSTOMER C ON O.O_CUSTKEY = C.C_CUSTKEY
WHERE C.C_NAME = '张三'
INTERSECT
SELECT P.P_PARTKEY, P.P_NAME
FROM PART P
JOIN LINEITEM LI ON P.P_PARTKEY = LI.L_PARTKEY
JOIN ORDERS O ON LI.L_ORDERKEY = O.O_ORDERKEY
JOIN CUSTOMER C ON O.O_CUSTKEY = C.C_CUSTKEY
WHERE C.C_NAME = '张三';
--并集
SELECT P.P_PARTKEY, P.P_NAME
FROM PART P
JOIN LINEITEM LI ON P.P_PARTKEY = LI.L_PARTKEY
JOIN ORDERS O ON LI.L_ORDERKEY = O.O_ORDERKEY
JOIN CUSTOMER C ON O.O_CUSTKEY = C.C_CUSTKEY
WHERE C.C_NAME = '张三'
INTERSECT
SELECT P.P_PARTKEY, P.P_NAME
FROM PART P
JOIN LINEITEM LI ON P.P_PARTKEY = LI.L_PARTKEY
JOIN ORDERS O ON LI.L_ORDERKEY = O.O_ORDERKEY
JOIN CUSTOMER C ON O.O_CUSTKEY = C.C_CUSTKEY
WHERE C.C_NAME = '张三';
--差集
SELECT P.P_PARTKEY, P.P_NAME
FROM PART P
JOIN LINEITEM LI ON P.P_PARTKEY = LI.L_PARTKEY
JOIN ORDERS O ON LI.L_ORDERKEY = O.O_ORDERKEY
JOIN CUSTOMER C ON O.O_CUSTKEY = C.C_CUSTKEY
WHERE C.C_NAME = '张三'
EXCEPT
SELECT P.P_PARTKEY, P.P_NAME
FROM PART P
JOIN LINEITEM LI ON P.P_PARTKEY = LI.L_PARTKEY
JOIN ORDERS O ON LI.L_ORDERKEY = O.O_ORDERKEY
JOIN CUSTOMER C ON O.O_CUSTKEY = C.C_CUSTKEY
WHERE C.C_NAME = '李四';

--（7）FROM 子句中的嵌套查询
SELECT C.*
FROM (
    SELECT O_CUSTKEY, AVG(O_TOTALPRICE) AS AVG_ORDER_PRICE
    FROM ORDERS
    GROUP BY O_CUSTKEY
    HAVING AVG(O_TOTALPRICE) > 10000
) AS T
JOIN CUSTOMER C ON T.O_CUSTKEY = C.C_CUSTKEY
JOIN NATION N ON C.C_NATIONKEY = N.N_NATIONKEY
WHERE N.N_NAME = '中国';
