-- 实验五

--（1）创建视图（省略视图列名）
-- 创建视图 V_DLMU_PartSupp1
CREATE VIEW V_DLMU_PartSupp1 AS
SELECT PS.PS_PARTKEY, P.P_NAME, PS.PS_AVAILQTY, P.P_RETAILPRICE, PS.PS_SUPPLYCOST, P.P_COMMENT
FROM PARTSUPP PS
JOIN PART P ON PS.PS_PARTKEY = P.P_PARTKEY
JOIN SUPPLIER S ON PS.PS_SUPPKEY = S.S_SUPPKEY
WHERE S.S_NAME = '海大汽配';

--（2）创建视图（不能省略列名的情况）
-- 创建视图 V_CustAvgOrder
CREATE VIEW V_CustAvgOrder AS
SELECT O_CUSTKEY AS C_CUSTKEY,
       C.C_NAME AS C_NAME,
       AVG(O_TOTALPRICE) AS AvgOrderPrice,
       AVG(NUMBER_OF_ITEMS) AS AvgNumOfItems
FROM (
    SELECT O_CUSTKEY,
           O_ORDERKEY,
           SUM(O_TOTALPRICE) AS O_TOTALPRICE,
           COUNT(DISTINCT L_PARTKEY) AS NUMBER_OF_ITEMS
    FROM ORDERS
    JOIN LINEITEM ON ORDERS.O_ORDERKEY = LINEITEM.L_ORDERKEY
    GROUP BY O_CUSTKEY, O_ORDERKEY
) AS OrderStats
JOIN CUSTOMER C ON OrderStats.O_CUSTKEY = C.C_CUSTKEY
GROUP BY O_CUSTKEY, C.C_NAME;

-- 创建视图 V_CustAvgOrder
CREATE VIEW V_CustAvgOrder AS
SELECT O_CUSTKEY AS C_CUSTKEY,
       C.C_NAME AS C_NAME,
       AVG(O_TOTALPRICE) AS AvgOrderPrice,
       AVG(NUMBER_OF_ITEMS) AS AvgNumOfItems
FROM (
    SELECT O_CUSTKEY,
           SUM(O_TOTALPRICE) AS O_TOTALPRICE,
           COUNT(DISTINCT L_PARTKEY) AS NUMBER_OF_ITEMS
    FROM ORDERS
    JOIN LINEITEM ON ORDERS.O_ORDERKEY = LINEITEM.L_ORDERKEY
    GROUP BY O_CUSTKEY
) AS OrderStats
JOIN CUSTOMER C ON OrderStats.O_CUSTKEY = C.C_CUSTKEY
GROUP BY O_CUSTKEY, C.C_NAME;

-- 删除视图 V_CustOrdDetails，并检查是否有其他对象依赖于它
DROP VIEW V_CustOrdDetails;

-- （4）创建一个行列子集可更新视图，并利用INSERT、DELETE和UPDATE语句加以验证

-- 创建一个行列子集可更新视图 V_Updated_PartSupp，只包含 PARTSUPP 表中的部分列
CREATE VIEW V_Updated_PartSupp AS
SELECT PS_PARTKEY, PS_AVAILQTY, PS_SUPPLYCOST
FROM PARTSUPP
WHERE PS_SUPPKEY = (SELECT S_SUPPKEY FROM SUPPLIER WHERE S_NAME = '海大汽配');

-- 尝试插入一条记录
INSERT INTO V_Updated_PartSupp (PS_PARTKEY, PS_AVAILQTY, PS_SUPPLYCOST) 
VALUES (1001, 50, 15.99);

-- 尝试删除一条记录
DELETE FROM V_Updated_PartSupp WHERE PS_PARTKEY = 1001;

-- 尝试更新一条记录
UPDATE V_Updated_PartSupp SET PS_AVAILQTY = 60 WHERE PS_PARTKEY = 1001;

-- （5）创建视图（WITH CHECK OPTION），并利用INSERT、DELETE和UPDATE语句加以验证

-- 创建一个视图 V_PartSupp_With_Check，带有 CHECK OPTION 选项，以确保插入的记录满足视图的条件
CREATE VIEW V_PartSupp_With_Check AS
SELECT *
FROM PARTSUPP
WHERE PS_SUPPLYCOST < 100
WITH CHECK OPTION;

-- 尝试插入一条记录
-- 由于视图限制了 PS_SUPPLYCOST 必须小于 100，插入的记录中的 PS_SUPPLYCOST 为 150，应该会失败
INSERT INTO V_PartSupp_With_Check (PS_PARTKEY, PS_SUPPKEY, PS_AVAILQTY, PS_SUPPLYCOST) 
VALUES (1002, 2, 50, 150);

-- 尝试删除一条记录
DELETE FROM V_PartSupp_With_Check WHERE PS_PARTKEY = 1001;

-- 尝试更新一条记录
UPDATE V_PartSupp_With_Check SET PS_AVAILQTY = 60 WHERE PS_PARTKEY = 1001;

-- （6）创建一个不可能更新的视图，并利用更新语句验证该视图不可更新

-- 创建一个不可能更新的视图 V_ReadOnly_Part，该视图与一个包含只读的基本表 PART 相关联
CREATE VIEW V_ReadOnly_Part AS
SELECT *
FROM PART
WHERE 1 = 0; -- 始终为假，因此该视图不会包含任何数据

-- 尝试插入一条记录
INSERT INTO V_ReadOnly_Part (P_PARTKEY, P_NAME, P_MFGR, P_BRAND, P_TYPE, P_SIZE, P_CONTAINER, P_RETAILPRICE, P_COMMENT) 
VALUES (10001, 'Part A', 'MFGR', 'Brand', 'Type', 10, 'Container', 100.00, 'Comment');

-- 尝试删除一条记录
DELETE FROM V_ReadOnly_Part WHERE P_PARTKEY = 10001;

-- 尝试更新一条记录
UPDATE V_ReadOnly_Part SET P_RETAILPRICE = 150.00 WHERE P_PARTKEY = 10001;