-- 实验一


-- 零件表
CREATE TABLE PART (
    P_PARTKEY CHAR(10) PRIMARY KEY,
    P_NAME VARCHAR(15),
    P_MFGR VARCHAR(15),
    P_BRAND VARCHAR(10),
    P_TYPE VARCHAR(15),
    P_SIZE FLOAT,
    P_CONTAINER CHAR(10),
    P_RETAILPRICE REAL,
    P_COMMENT VARCHAR(100)
);


-- 供应商表
CREATE TABLE SUPPLIER (
    S_SUPPKEY CHAR(10) PRIMARY KEY,
    S_NAME VARCHAR(15),
    S_ADDRESS VARCHAR(40),
    S_NATIONKEY CHAR(3),
    S_PHONE CHAR(15),
    S_ACCTBAL REAL,
    S_COMMENT VARCHAR(100)
);


-- 供应商-零件表
CREATE TABLE PARTSUPP (
    PS_PARTKEY CHAR(10),
    PS_SUPPKEY CHAR(10),
    PS_AVAILQTY INTEGER,
    PS_SUPPLYCOST REAL,
    PS_COMMENT VARCHAR(100),
    PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY),
    FOREIGN KEY (PS_PARTKEY) REFERENCES PART(P_PARTKEY),
    FOREIGN KEY (PS_SUPPKEY) REFERENCES SUPPLIER(S_SUPPKEY)
);


-- 地区表
CREATE TABLE REGION (
    R_REGIONKEY CHAR(4) PRIMARY KEY,
    R_NAME CHAR(25),
    R_COMMENT VARCHAR(100)
);


-- 国家表
CREATE TABLE NATION (
    N_NATIONKEY CHAR(3) PRIMARY KEY,
    N_NAME VARCHAR(25),
    N_REGIONKEY CHAR(4),
    N_COMMENT VARCHAR(100),
    FOREIGN KEY (N_REGIONKEY) REFERENCES REGION(R_REGIONKEY)
);


-- 客户表
CREATE TABLE CUSTOMER (
    C_CUSTKEY CHAR(10) PRIMARY KEY,
    C_NAME VARCHAR(15),
    C_ADDRESS VARCHAR(40),
    C_NATIONKEY CHAR(3),
    C_PHONE CHAR(15),
    C_ACCTBAL REAL,
    C_MKTSEGMENT CHAR(20),
    C_COMMENT VARCHAR(100),
    FOREIGN KEY (C_NATIONKEY) REFERENCES NATION(N_NATIONKEY)
);


-- 订单表
CREATE TABLE ORDERS (
    O_ORDERKEY CHAR(10) PRIMARY KEY,
    O_CUSTKEY CHAR(10),
    O_ORDERSTATUS CHAR(1),
    O_TOTALPRICE REAL,
    O_ORDERDATE DATE,
    O_ORDERPRIORITY CHAR(15),
    O_CLERK CHAR(15),
    O_SHIPPRIORITY CHAR(3),
    O_COMMENT VARCHAR(100),
    FOREIGN KEY (O_CUSTKEY) REFERENCES CUSTOMER(C_CUSTKEY)
);


-- 订单明细表
CREATE TABLE LINEITEM (
    L_ORDERKEY CHAR(10),
    L_PARTKEY CHAR(10),
    L_SUPPKEY CHAR(10),
    L_LINENUMBER CHAR(10),
    L_QUANTITY INTEGER,
    L_EXTENDEDPRICE REAL,
    L_DISCOUNT REAL,
    L_TAX REAL,
    L_RETURNFLAG CHAR(1),
    L_LINESTATUS CHAR(1),
    L_SHIPDATE DATE,
    L_COMMITDATE DATE,
    L_RECEIPTDATE DATE,
    L_SHIPINSTRUCT CHAR(25),
    L_SHIPMODE CHAR(10),
    L_COMMENT VARCHAR(100),
    PRIMARY KEY (L_ORDERKEY, L_LINENUMBER),
    FOREIGN KEY (L_ORDERKEY) REFERENCES ORDERS(O_ORDERKEY),
    FOREIGN KEY (L_PARTKEY) REFERENCES PART(P_PARTKEY), 
    FOREIGN KEY (L_SUPPKEY) REFERENCES SUPPLIER(S_SUPPKEY) 
);



